[theme]
base = "light"
primaryColor = "#FF5A36"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
